# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://brunopaixao.dev/
baseurl: 
title: Bruno Paixão - Developer
author: Bruno Paixão
description: Blog Pessoal
avatar: profile.png
email: brunopaixao87@email.com
github: brunopaixao87 # username
twitter: brunopaixaodev
linkedin: bruno-cruz-da-paix%C3%A3o-642b7359/
instagram: brunocdpaixao
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-135965173-1


# needed for travis-ci build
exclude: [vendor]
