# Site settings
title: Blog pessoal Bruno Paixão
description: Blog pessoal Bruno Paixão
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g.

# User settings
username: Bruno Paixão
user_description: Software Craftsman and Enthusiast Data Science 
user_title: Software Craftsman
email: brunopaixao87@gmail.com
twitter_username: brunopaixaobp
github_username:  brunopaixao87
gplus_username:  brunopaixao87

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
